version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
    time: "06:00"
    timezone: Europe/Amsterdam
  open-pull-requests-limit: 25
  reviewers:
  - mprins
  assignees:
  - mprins
  - mtoonen
  ignore:
  - dependency-name: com.fasterxml.jackson.core:jackson-databind
    versions:
    - ">= 2.10.x"
    
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 5
  reviewers:
  - mprins
  assignees:
  - mprins
